One-hot encoding is a technique used to represent categorical labels as binary vectors. 

### **How One-Hot Encoding Works?**
- Given a set of **N** possible classes (e.g., digits 0-9 → **10 classes** for MNIST).
- Each class is represented as a **binary vector** of length **N**, where:
  - The position corresponding to the class index is **1**.
  - All other positions are **0**.

---

### **Example: One-Hot Encoding of Digit '3'**
For MNIST, the classes are:  
`[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]` (10 classes)

To one-hot encode **3**, we create a vector of size **10** where only the **4th position (index 3)** is **1**, and the rest are **0**:

```
Label = 3
One-Hot Encoding → [0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
```

### **Other Examples**
| Label | One-Hot Encoded Vector |
|--------|-------------------------|
| **0**  | `[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]` |
| **1**  | `[0, 1, 0, 0, 0, 0, 0, 0, 0, 0]` |
| **2**  | `[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]` |
| **3**  | `[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]` |
| **4**  | `[0, 0, 0, 0, 1, 0, 0, 0, 0, 0]` |

---

### **One-Hot Encoding in Python (Keras)**
You can convert integer labels into one-hot vectors using **`to_categorical`**:
```python
from tensorflow.keras.utils import to_categorical
import numpy as np

# Example labels (digits)
y_train = np.array([0, 1, 2, 3, 4])

# Convert to one-hot encoded format
y_train_one_hot = to_categorical(y_train, num_classes=10)

print(y_train_one_hot)
```

### **Output**
```
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
```
